### ISSUE TITLE
Documentation Woke Issue ezLCD-5xxx LUA API Manual.docx

### ISSUE THREAD

**Issue by randy-earthlcd** [earthlcd/ezLCD-5xxx-Beta-Firmware#23]
ezLCD-5xxx LUA API Manual.docx   change name to ezLCD-5x LUA Manual.docx   
Change and replace all 5xxx references to 5x
Change file name to replace 5xxx with 5x and remove API from file name

**Comment by microlan** [comment]
Fixed
